[package]
name = "algexeno_cistercian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
algexenotation = "0.3.0"

[dev-dependencies]
piston_window = "0.124.0"
